### ISSUE TITLE
Import statements incompatible with both CLI and Pytest

### ISSUE THREAD

**Issue by audreyyku** [ukyerdua/geosimilarity#4]
### In compare.py and in similarity.py, when the helper functions are imported like below:
**```from linestring_tools import line_to_coords```**
the CLI runs with no errors, but pytest raises a "ModuleNotFoundError" for linestring_tools.
```
pytest

======================================================================================== test session starts ========================================================================================
platform darwin -- Python 3.6.5, pytest-6.1.0, py-1.9.0, pluggy-0.13.1
rootdir: /Users/audreyku/Desktop/coding_challenge/geosimilarity
collected 3 items / 2 errors / 1 selected                                                                                                                                                           

============================================================================================== ERRORS ===============================================================================================
______________________________________________________________________________ ERROR collecting tests/test_compare.py _______________________________________________________________________________
ImportError while importing test module '/Users/audreyku/Desktop/coding_challenge/geosimilarity/tests/test_compare.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../.pyenv/versions/3.6.5/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_compare.py:7: in <module>
    from geosimilarity import compare
geosimilarity/compare.py:4: in <module>
    from linestring_tools import line_to_coords
E   ModuleNotFoundError: No module named 'linestring_tools'
_____________________________________________________________________________ ERROR collecting tests/test_similarity.py _____________________________________________________________________________
ImportError while importing test module '/Users/audreyku/Desktop/coding_challenge/geosimilarity/tests/test_similarity.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../.pyenv/versions/3.6.5/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_similarity.py:8: in <module>
    from geosimilarity import similarity
geosimilarity/similarity.py:3: in <module>
    from compare import compare
E   ModuleNotFoundError: No module named 'compare'
====================================================================================== short test summary info ======================================================================================
ERROR tests/test_compare.py
ERROR tests/test_similarity.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================================= 2 errors in 0.73s =========================================================================================
```

### However, once you revise the import statement to resemble the following:
**```from .linestring_tools import line_to_coords```**
or
**```from geosimilarity.linestring_tools import line_to_coords```**

All of the pytest tests pass, but the CLI will raise an ImportError.
```
$ bin/geosimilarity compare data/test_compare_files/test_compare1
Traceback (most recent call last):
  File "bin/../geosimilarity/main.py", line 7, in <module>
    from compare import compare as _compare
  File "/Users/audreyku/Desktop/coding_challenge/geosimilarity/geosimilarity/compare.py", line 4, in <module>
    from .linestring_tools import line_to_coords
ImportError: attempted relative import with no known parent package
```
```
$ bin/geosimilarity compare data/test_compare_files/test_compare1
Traceback (most recent call last):
  File "bin/../geosimilarity/main.py", line 7, in <module>
    from compare import compare as _compare
  File "/Users/audreyku/Desktop/coding_challenge/geosimilarity/geosimilarity/compare.py", line 4, in <module>
    from geosimilarity.linestring_tools import line_to_coords
ModuleNotFoundError: No module named 'geosimilarity'
```
```
$ bin/geosimilarity compare data/test_compare_files/test_compare1
Traceback (most recent call last):
  File "bin/../geosimilarity/main.py", line 7, in <module>
    from compare import compare as _compare
  File "/Users/audreyku/Desktop/coding_challenge/geosimilarity/geosimilarity/compare.py", line 3, in <module>
    import geosimilarity
ModuleNotFoundError: No module named 'geosimilarity'
```

**Comment by audreyyku** [comment]
By setting the PYTHONPATH to the folder containing the code, pytest and the CLI both work without any import issues.
```export PYTHONPATH="$PWD/geosimilarity"```
Added this statement to the **Setup** section of the README.
